# cmake/SherpaOnnx.cmake
# Locate pre-built sherpa-onnx libraries downloaded by scripts/setup-sherpa-onnx.sh
# and create an IMPORTED target `sherpa_onnx::c_api` for linking.

# Default to the repo's extern/, but allow a caller (e.g. the standalone server
# project) to point this at the repo root before include()-ing this module.
if(NOT DEFINED SHERPA_ONNX_ROOT)
    set(SHERPA_ONNX_ROOT "${CMAKE_SOURCE_DIR}/extern/sherpa-onnx")
endif()
set(SHERPA_ONNX_INCLUDE_DIR "${SHERPA_ONNX_ROOT}/include")

# ── Determine library sub-directory for the current target ────────────────────
if(WIN32)
    set(_SHERPA_LIB_DIR "${SHERPA_ONNX_ROOT}/lib/win-x64")
else()
    if(CMAKE_SYSTEM_PROCESSOR MATCHES "aarch64|arm64")
        set(_SHERPA_LIB_DIR "${SHERPA_ONNX_ROOT}/lib/linux-aarch64")
    else()
        set(_SHERPA_LIB_DIR "${SHERPA_ONNX_ROOT}/lib/linux-x64")
    endif()
endif()

# ── Validate setup ────────────────────────────────────────────────────────────
if(NOT EXISTS "${SHERPA_ONNX_INCLUDE_DIR}/sherpa-onnx/c-api/c-api.h")
    message(FATAL_ERROR
        "sherpa-onnx headers not found.\n"
        "Run: ./scripts/setup-sherpa-onnx.sh\n"
        "Expected: ${SHERPA_ONNX_INCLUDE_DIR}/sherpa-onnx/c-api/c-api.h")
endif()

if(NOT EXISTS "${_SHERPA_LIB_DIR}")
    message(FATAL_ERROR
        "sherpa-onnx libraries not found for this platform.\n"
        "Run: ./scripts/setup-sherpa-onnx.sh\n"
        "Expected: ${_SHERPA_LIB_DIR}/")
endif()

# ── Platform-specific target setup ────────────────────────────────────────────
if(WIN32)
    # ── Windows: shared library (DLL) ─────────────────────────────────────────
    add_library(sherpa_onnx_c_api SHARED IMPORTED GLOBAL)

    # Prefer MinGW import library if generated by setup script
    if(EXISTS "${_SHERPA_LIB_DIR}/libsherpa-onnx-c-api.dll.a")
        set_target_properties(sherpa_onnx_c_api PROPERTIES
            IMPORTED_LOCATION "${_SHERPA_LIB_DIR}/sherpa-onnx-c-api.dll"
            IMPORTED_IMPLIB   "${_SHERPA_LIB_DIR}/libsherpa-onnx-c-api.dll.a"
        )
    else()
        # Fall back to direct DLL linking (MinGW can do this)
        set_target_properties(sherpa_onnx_c_api PROPERTIES
            IMPORTED_LOCATION "${_SHERPA_LIB_DIR}/sherpa-onnx-c-api.dll"
            IMPORTED_IMPLIB   "${_SHERPA_LIB_DIR}/sherpa-onnx-c-api.lib"
        )
    endif()

    target_include_directories(sherpa_onnx_c_api INTERFACE "${SHERPA_ONNX_INCLUDE_DIR}")

    # Collect all DLLs that must be shipped with the executable
    file(GLOB SHERPA_ONNX_DLLS "${_SHERPA_LIB_DIR}/*.dll")
    set(SHERPA_ONNX_RUNTIME_DLLS ${SHERPA_ONNX_DLLS} CACHE STRING "sherpa-onnx DLLs to ship" FORCE)

else()
    # ── Linux: static libraries ───────────────────────────────────────────────
    # Link order matters for static archives.
    set(_SHERPA_STATIC_LIBS
        sherpa-onnx-c-api
        sherpa-onnx-core
        kaldi-decoder-core
        sherpa-onnx-kaldifst-core
        sherpa-onnx-fst
        sherpa-onnx-fstfar
        kaldi-native-fbank-core
        ssentencepiece_core
        kissfft-float
        onnxruntime
    )

    # Create individual IMPORTED targets for each static library
    foreach(_lib ${_SHERPA_STATIC_LIBS})
        set(_lib_path "${_SHERPA_LIB_DIR}/lib${_lib}.a")
        if(NOT EXISTS "${_lib_path}")
            message(WARNING "sherpa-onnx static library not found: ${_lib_path}")
            continue()
        endif()
        add_library(sherpa_onnx_${_lib} STATIC IMPORTED GLOBAL)
        set_target_properties(sherpa_onnx_${_lib} PROPERTIES
            IMPORTED_LOCATION "${_lib_path}"
        )
    endforeach()

    # Create umbrella interface target
    add_library(sherpa_onnx_c_api INTERFACE IMPORTED GLOBAL)
    target_include_directories(sherpa_onnx_c_api INTERFACE "${SHERPA_ONNX_INCLUDE_DIR}")

    set(_link_list "")
    foreach(_lib ${_SHERPA_STATIC_LIBS})
        if(TARGET sherpa_onnx_${_lib})
            list(APPEND _link_list sherpa_onnx_${_lib})
        endif()
    endforeach()
    # System libs required by onnxruntime
    list(APPEND _link_list dl m)

    set_target_properties(sherpa_onnx_c_api PROPERTIES
        INTERFACE_LINK_LIBRARIES "${_link_list}"
    )
endif()

# Create a namespaced alias
add_library(sherpa_onnx::c_api ALIAS sherpa_onnx_c_api)

message(STATUS "sherpa-onnx: headers  = ${SHERPA_ONNX_INCLUDE_DIR}")
message(STATUS "sherpa-onnx: libs     = ${_SHERPA_LIB_DIR}")
